version: '3'

services:
  db:
    image: postgres:10.1-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    build: .
    command: bash -c "sleep 5 && python manage.py makemigrations && python manage.py migrate && python manage.py test movies && gunicorn app.wsgi:application -b '0.0.0.0:8000' -w 2 --log-file -"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      OMDBAPIKEY: ${OMDBAPIKEY}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
