# Generated by Django 2.2.1 on 2019-05-28 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['movie', 'created']},
        ),
        migrations.AlterModelOptions(
            name='movierating',
            options={'ordering': ['movie', 'source']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 17, 39, 57, 198545, tzinfo=utc)),
        ),
    ]
